name: gepi
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase (si tu en as encore besoin pendant la migration)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0

  # Supabase + dotenv
  supabase_flutter: ^2.10.0
  flutter_dotenv: ^6.0.0
  printing: ^5.14.2
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  open_file: ^3.5.10
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
