// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa4QvLFzGLR7vD6-WTTyQR7dbuDGhrQIQ',
    appId: '1:292161627006:web:bd3bf0a08a4178b4b3c92f',
    messagingSenderId: '292161627006',
    projectId: 'gepi-47831',
    authDomain: 'gepi-47831.firebaseapp.com',
    storageBucket: 'gepi-47831.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWtpSrxfvLFpA-OWeP36yZ5jAbujoY288',
    appId: '1:292161627006:android:831248d28be4b470b3c92f',
    messagingSenderId: '292161627006',
    projectId: 'gepi-47831',
    storageBucket: 'gepi-47831.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoqOlT2eVNIHaZtNN52-WQBGHJ5luuMyk',
    appId: '1:292161627006:ios:8ae8ea88e105d5b1b3c92f',
    messagingSenderId: '292161627006',
    projectId: 'gepi-47831',
    storageBucket: 'gepi-47831.firebasestorage.app',
    iosBundleId: 'com.domain.gepi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoqOlT2eVNIHaZtNN52-WQBGHJ5luuMyk',
    appId: '1:292161627006:ios:8ae8ea88e105d5b1b3c92f',
    messagingSenderId: '292161627006',
    projectId: 'gepi-47831',
    storageBucket: 'gepi-47831.firebasestorage.app',
    iosBundleId: 'com.domain.gepi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa4QvLFzGLR7vD6-WTTyQR7dbuDGhrQIQ',
    appId: '1:292161627006:web:5ebb9fac1ffaeb5cb3c92f',
    messagingSenderId: '292161627006',
    projectId: 'gepi-47831',
    authDomain: 'gepi-47831.firebaseapp.com',
    storageBucket: 'gepi-47831.firebasestorage.app',
  );
}
